
font_dict = {
    "treble_clef":u"\uE050",
    "whole_note_head":u"\uE0A2",
    "open_note_head":u"\uE0A3",
    "solid_note_head":u"\uE0A4",
    "single_aug_dot":u"\uECB7",
    "double_aug_dot":u"\uECB7",#needs to be updated
    "single_flag_down":u"\uE241",
    "single_flag_up":u"\uE240",
    "double_flag_down":u"\uE243",
    "double_flag_up":u"\uE242",
    "triple_flag_down":u"\uE245",
    "triple_flag_up":u"\uE244",
    "single_sharp":u"\uE262",
    "single_flat":u"\uE260",
    "single_natural":u"\uE261",
    "double_sharp":u"\uE263",
    "double_flat":u"\uE264",
    "double_natural":u"\uE261",#do we have double natural?
    "time_0":u"\uE080",
    "time_1":u"\uE081",
    "time_2":u"\uE082",
    "time_3":u"\uE083",
    "time_4":u"\uE084",
    "time_5":u"\uE085",
    "time_6":u"\uE086",
    "time_7":u"\uE087",
    "time_8":u"\uE088",
    "time_9":u"\uE089",
    "time_common":u"\uE08A",
    "time_cut":u"\uE08B",
    "bar":-1,
    "double_bar":-1,
    "stem":-1,
    "beam":-1,
    "part_beam":-1,
    "ledger_line":-1
}
